# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Leisure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Leisure
  
  pod 'SDWebImage'
  pod 'SwiftLint'

  target 'LeisureTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
